name: Node test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout VALVE
      uses: actions/checkout@v2
      with:
        repository: ontodev/valve
        path: valve-main
        ref: tests
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm i -g . && cat requirements.txt | xargs npm i -g
    - name: Unit Test
      run: |
        npm test
    - name: Integration Test
      run: |
        make node-diff
    - name: Integration Test Distinct
      run: |
        make node-diff-distinct